name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux_sp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make FOO=-fno-stack-protector

  build_run_linux_sp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make FOO=-fno-stack-protector
    - name: run
      run: ./main skip

  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

  build_run_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: run
      run: ./main skip

  run_win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: main
      run: ./main.exe skip
